"""empty message

Revision ID: a5d36542a601
Revises: 3fbec9e642e0
Create Date: 2019-06-10 13:48:21.548481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5d36542a601'
down_revision = '3fbec9e642e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('status_dialog', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'status_dialog')
    # ### end Alembic commands ###
